ip = '127.0.0.1'
port = 8000
createdirs = false
db = './zknotes.db'
mainsite = 'http://localhost:8000'
altmainsite = []
appname = 'zknotes'
domain = 'localhost:8000'
admin_email = 'admin@admin.admin'
login_token_expiration_ms = 604800000
email_token_expiration_ms = 86400000
reset_token_expiration_ms = 86400000
